### ISSUE TITLE
Moving from Fire

### ISSUE THREAD

**Issue by ndpete** [byu-oit/awslogin#16]
Not really an issue just something I'd like discussion on.

I wonder if we would be better served by moving away from Fire as our CLI to something like Plac.
Fire is a great library for taking lots of functions and turning them into a cli suite however as such it makes some things a little weird with our case. 

For example the help command isn't very intuitive and doesn't really follow normal cli patterns
`awslogin --help` doesn't actual output any help. It executes the program and then ends with a key error. The command to print the help page is `awslogin -- --help` and even that output only slightly resembles a normal help file:
```sh
ndpete@Loki > ~ > awslogin -- --help
Type:        function
String form: <function cli at 0x10af61840>
File:        /usr/local/lib/python3.6/site-packages/byu_awslogin/index.py
Line:        27

Usage:       awslogin [ACCOUNT] [ROLE] [PROFILE]
             awslogin [--account ACCOUNT] [--role ROLE] [--profile PROFILE]
```

In contrast an example help output from a plac app I previously wrote:
```sh
ndpete@Loki > ~ > ./repometa-counts.py --help
usage: repometa-counts.py [-h] [-o OUTPUT_FILE] [-d] git_org

positional arguments:
  git_org               github org to check

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUT_FILE, --output-file OUTPUT_FILE
                        File to output full data to
  -d, --debug           Run against test cmdb instance
```

I don't know maybe its just nit picking but I'd love to hear other people's thoughts. Also I'm more then willing to do the refactor. It shouldn't take much effort at all as Plac and Fire are similiar in implementation

**Comment by pauldeden** [comment]
I'm supportive of this change.

**Comment by dsw88** [comment]
Sounds good to me, I look forward to the improved help functionality!
