### ISSUE TITLE
Figure out how to persist logins for up to 8 hours, similar to browser behavior

### ISSUE THREAD

**Issue by dsw88** [byu-oit/awslogin#19]
On the browser, you can log into ADFS once, and thereafter for 8 hours it will bypass ADFS authentication page and go straight to the AWS roles page. I assume it is doing this via some mechanism like cookies from the original login being sent to the server.

We need this in awslogin because it would be so great to just type "awslogin" for 8 hours and not have to do any of the username/password or DUO auth!

**Comment by ndpete** [comment]
I looked at my cookies on my browser and notice they were all set to expire when the browsing session ends. To test I closed my browser completely and upon reopening and trying to get to AWS I was prompted to login again.

I'm not sure how request and what not handle sessions and cookies. Just thought I'd share my findings.
