### ISSUE TITLE
Reset Profile Functionality

### ISSUE THREAD

**Issue by kwcrook** [byu-oit/awslogin#2]
Feature Request

Various issues caused by outdated MFA tokens require users to go to their user folder and delete the profile data.

Requesting something like what "aws-adfs reset" did.

**Comment by dsw88** [comment]
We're not doing caching in this library currently like aws-adfs was, so this feature isn't needed currently. We may add caching in the future, but hopefully it will be implemented in such a way that we won't need aws-adfs reset. I'm closing this issue for now, and we can reopen it later if needed.
