### ISSUE TITLE
ADFS auth cache is stored improperly

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/awslogin#24]
The adfs_auth value in the credentials file is base64-encoded, but it is not done using URL-safe Base64, which means that the value spans multiple lines.  Because the other lines aren't like key=value, this causes problems in the Java AWS SDK, which aggressively validates the file as it loads it.

I believe the problem is here:

https://github.com/byu-oit/awslogin/blob/9c5a42e8aaa0d53473e02ade3a6bc3c77c00b01c/byu_awslogin/util/data_cache.py#L26

I would just hand you a PR, but I don't know enough about the python standard lib to fix this.

**Comment by pauldeden** [comment]
@ThatJoeMoore this fix is now in version 0.12.1 of byu_awslogin (the newest version).  I have tested the new version manually in addition to the unit test in the pull request and the adfs_auth line in my ~/.aws/credentials file is only one line.

Upgrade by running `pip3 install --upgrade byu_awslogin`

Let us know if this doesn't fix the problem with the Java AWS SDK.  Thanks.
