### ISSUE TITLE
Add a logout option

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/awslogin#29]
Since we keep people logged in for 8 hours now, there are times when we need to logout and login again with a different net_id in that timeframe.

**Comment by dsw88** [comment]
While this feature gets implemented, here's an easy workaround to log out:
```
rm ~/.aws/credentials
```

**Comment by dsw88** [comment]
Be aware that workaround logs you out of all accounts, meaning that it deletes all your AWS credentials from your local computer. If you have some from a personal account it'll delete those too. :)
