### ISSUE TITLE
-- proxy

### ISSUE THREAD

**Issue by wiederhold** [byu-oit/awslogin#34]
Platform team has need of a proxy switch to allow us to run awslogin from within the Inner Zone, something along the lines of the following:

`
import os
import re
import sys

os.environ['http_proxy'] = "east.byu.edu:3128"
os.environ['HTTP_PROXY'] = "east.byu.edu:3128"
os.environ['https_proxy'] = "east.byu.edu:3128"
os.environ['HTTPS_PROXY'] = "east.byu.edu:3128"

from byu_awslogin.index import cli

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
~                                                                        
`

**Comment by ndpete** [comment]
So if i'm reading that correctly the only thing the `--proxy` option would do would be to set the 4 environment variables?
Would they always be `east.byu.edu:3128`  or would you specify the proxy after `--proxy`

**Comment by wiederhold** [comment]
correct
