### ISSUE TITLE
Remove prd-id-oit-byu from list of avail accounts

### ISSUE THREAD

**Issue by wiederhold** [byu-oit/awslogin#43]
prd-id-oit-byu needs to  be removed from the list of accounts

awslogin -a all -r Administrator   [version 0.13.2] gives me a helpful
'you don't have access to that, so I'm going to skip it' message for account 116585688941

BUT

awslogin -a all -r ReadOnly  chokes:

` _perform_login(adfs_auth_result, saml_assertion, account, role, profile, None, region)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/byu_awslogin/login.py", line 46, in _perform_login
    aws_session_token = assume_role(account_role_to_assume, saml_assertion.assertion)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/byu_awslogin/auth/assume_role.py", line 33, in assume_role
    DurationSeconds=3600,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithSAML operation: User null is not authorized to perform: sts:AssumeRoleWithSAML on resource: arn:aws:iam::116585688941:role/ReadOnly`

**Comment by ndpete** [comment]
I think this is an issue with the ADFS Sign-on Page as I can get the same error logging in from the browser, and the awslogin command just calls the same sign-on page.

![screen shot 2018-01-16 at 11 28 00 am](https://user-images.githubusercontent.com/4553244/35005363-67246a70-fab0-11e7-9e08-8494f411e8ce.png)

Anybody know how that all works?

**Comment by bwinterton** [comment]
I am quite certain that this has to do with our AD server and the configuration between it and AWS. awslogin does not have a list of allowed accounts, but receives it from the SAML response from AD.

**Comment by ndpete** [comment]
I contacted @evade-ninja and he clean up the AD/ADFS and removed the old account. I then tested logging in to all accounts and it worked as expected.
