### ISSUE TITLE
Logout Status Not Working

### ISSUE THREAD

**Issue by teranpeterson** [byu-oit/awslogin#61]
After logging out, awslogin -s returns the same information as before.
```
awslogin -s
PowerUser@dev-oit-byu - Expires at: 07-16-2019 01:25
awslogin --logout
Terminated ADFS Session
awslogin -s
PowerUser@dev-oit-byu - Expires at: 07-16-2019 01:25

**Comment by ndpete** [comment]
As is stated in your output and the help text `--logout` only terminates the ADFS Session. It doesn't invalidate or remove any of the temporary access token that are generated.
